/*
 Generated by typeshare 1.13.3
*/

export enum ChatMode {
	Normal = 'normal',
	Search = 'search',
	Research = 'research'
}

export interface ChatCreateReq {
	model_id: number;
	mode: ChatMode;
}

export interface ChatCreateResp {
	id: number;
}

export interface ChatDeleteReq {
	id: number;
}

export interface ChatDeleteResp {
	deleted: boolean;
}

export interface ChatHaltReq {
	id: number;
}

export interface ChatHaltResp {}

export enum ChatPaginateReqOrder {
	/** greater than */
	Gt = 'gt',
	/** less than */
	Lt = 'lt'
}

export interface ChatPaginateReqLimit {
	/**
	 * Default to the beginning
	 * For Gt => minimum id
	 * For Le => maximum id
	 */
	id?: number;
	order: ChatPaginateReqOrder;
	limit?: number;
}

/**
 * Does not include upper & lower
 * lower [... return items ... ] upper
 */
export interface ChatPaginateReqRange {
	upper: number;
	lower: number;
}

export interface ChatPaginateRespList {
	id: number;
	model_id?: number;
	title?: string;
}

export interface ChatPaginateResp {
	list: ChatPaginateRespList[];
}

export interface ChatReadReq {
	id: number;
}

export interface ChatReadResp {
	mode: ChatMode;
	model_id?: number;
	title?: string;
}

export interface ChatUpdateReq {
	chat_id: number;
	title?: string;
}

export interface ChatUpdateResp {
	wrote: boolean;
}

export enum StepKind {
	Code = 'code',
	Research = 'research'
}

export type AssistantChunk =
	| { t: 'annotation'; c: string }
	| { t: 'text'; c: string }
	| { t: 'reasoning'; c: string }
	| {
			t: 'tool_call';
			c: {
				id: string;
				arg: string;
				name: string;
			};
	  }
	| {
			t: 'tool_result';
			c: {
				id: string;
				response: string;
			};
	  }
	| { t: 'error'; c: string }
	| { t: 'deep_agent'; c: Deep };

export interface Step {
	need_search: boolean;
	title: string;
	description: string;
	kind: StepKind;
	progress: AssistantChunk[];
}

export interface Deep {
	locale: string;
	has_enough_context: boolean;
	thought: string;
	title: string;
	steps: Step[];
}

export enum ErrorKind {
	Unauthorized = 'unauthorized',
	MalformedToken = 'malformed_token',
	MalformedRequest = 'malformed_request',
	Internal = 'internal',
	LoginFail = 'login_fail',
	ResourceNotFound = 'resource_not_found',
	ApiFail = 'api_fail',
	ToolCallFail = 'tool_call_fail'
}

export interface Error {
	error: ErrorKind;
	reason: string;
}

export interface FileMetadata {
	name: string;
	id: number;
}

export interface FileUploadResp {
	id: number;
}

export interface LoginReq {
	username: string;
	password: string;
}

export interface LoginResp {
	token: string;
	exp: string;
}

export interface MessageCreateReqFile {
	id: number;
	name: string;
}

export interface MessageCreateReq {
	chat_id: number;
	model_id: number;
	mode: ChatMode;
	text: string;
	files: MessageCreateReqFile[];
}

export interface MessageCreateResp {
	id: number;
	user_id: number;
}

export interface MessageDeleteReq {
	id: number;
}

export enum MessagePaginateReqOrder {
	/** greater than */
	Gt = 'gt',
	/** less than */
	Lt = 'lt'
}

export interface MessagePaginateReqLimit {
	chat_id: number;
	/** default to i32::MAX */
	id?: number;
	order: MessagePaginateReqOrder;
	limit?: number;
}

/**
 * Does not include upper & lower
 * lower [... return items ... ] upper
 */
export interface MessagePaginateReqRange {
	chat_id: number;
	upper: number;
	lower: number;
}

export type MessageInner =
	| {
			t: 'user';
			c: {
				text: string;
				files: FileMetadata[];
			};
	  }
	| { t: 'assistant'; c: AssistantChunk[] };

export interface MessagePaginateRespList {
	id: number;
	token_count: number;
	price: number;
	inner: MessageInner;
}

export interface MessagePaginateResp {
	list: MessagePaginateRespList[];
}

export interface ModelCheckReq {
	config: string;
}

export interface ModelCheckResp {
	reason?: string;
}

export interface ModelCreateReq {
	config: string;
}

export interface ModelCreateResp {
	id: number;
	display_name: string;
	image_input: boolean;
	audio_input: boolean;
	other_file_input: boolean;
}

export interface ModelDeleteReq {
	id: number;
}

export interface ModelDeleteResp {
	deleted: boolean;
}

export interface ModelList {
	id: number;
	display_name: string;
	image_input: boolean;
	audio_input: boolean;
	other_file_input: boolean;
}

export interface ModelListReq {}

export interface ModelListResp {
	list: ModelList[];
}

export interface ModelReadReq {
	id: number;
}

export interface ModelReadResp {
	raw: string;
}

export interface ModelWriteReq {
	id: number;
	config: string;
}

export interface ModelWriteResp {
	display_name: string;
	wrote: boolean;
}

export interface RenewReq {
	token: string;
}

export interface RenewResp {
	token: string;
	exp: string;
}

export interface Resp {
	deleted: boolean;
}

export interface SseReq {
	id: number;
}

export interface SseRespDeepPlan {
	content: string;
}

export interface SseRespDeepReport {
	content: string;
}

export interface SseRespDeepStep {
	content: string;
}

export interface SseRespError {
	content: string;
}

export interface SseRespMessageComplete {
	id: number;
	token_count: number;
	cost: number;
	version: number;
}

export interface SseRespReasoning {
	content: string;
}

export interface SseRespTitle {
	title: string;
}

export interface SseRespToken {
	content: string;
}

export interface SseRespToolCall {
	name: string;
	args: string;
}

export interface SseRespToolResult {
	content: string;
}

export interface SseRespToolToken {
	content: string;
}

export interface SseRespVersion {
	version: number;
}

export interface SseStart {
	id: number;
	user_msg_id: number;
	version: number;
}

export interface UserCreateReq {
	username: string;
	password: string;
}

export interface UserCreateResp {
	user_id: number;
}

export interface UserDeleteReq {
	user_id: number;
}

export interface UserDeleteResp {
	deleted: boolean;
}

export interface UserList {
	id: number;
	name: string;
}

export interface UserListReq {}

export interface UserListResp {
	list: UserList[];
}

export interface UserPreference {
	theme?: string;
	locale?: string;
	submit_on_enter?: string;
}

export interface UserReadReq {
	/** If omit will use the current user instead */
	user_id?: number;
}

export interface UserReadResp {
	user_id: number;
	username: string;
	preference: UserPreference;
}

export interface UserUpdateReq {
	/** If omit will use the current user instead */
	user_id?: number;
	preference?: UserPreference;
	password?: string;
}

export interface UserUpdateResp {
	user_id: number;
}

export type ChatPaginateReq =
	| { t: 'limit'; c: ChatPaginateReqLimit }
	| { t: 'range'; c: ChatPaginateReqRange };

export type MessagePaginateReq =
	| { t: 'limit'; c: MessagePaginateReqLimit }
	| { t: 'range'; c: MessagePaginateReqRange };

export type SseResp =
	| { t: 'version'; c: number }
	| { t: 'token'; c: string }
	| { t: 'reasoning'; c: string }
	| { t: 'tool_call'; c: SseRespToolCall }
	| { t: 'tool_token'; c: string }
	| { t: 'tool_result'; c: SseRespToolResult }
	| { t: 'complete'; c: SseRespMessageComplete }
	| { t: 'title'; c: string }
	| { t: 'error'; c: string }
	| { t: 'start'; c: SseStart }
	| { t: 'deep_plan'; c: string }
	| { t: 'deep_step_start'; c: string }
	| { t: 'deep_step_token'; c: string }
	| { t: 'deep_step_reasoning'; c: string }
	| { t: 'deep_step_tool_call'; c: SseRespToolCall }
	| { t: 'deep_step_tool_token'; c: string }
	| { t: 'deep_report'; c: string };
