set shell := ["nu", "-c"]

TS_OUTPUT := "../frontend/src/lib/api/types.ts"

DATABASE_URL := "sqlite://../db.sqlite?mode=rwc"


run:
    RUST_BACKTRACE=1 cargo run --features dev

fresh:
    cd migration; DATABASE_URL={{DATABASE_URL}} cargo run -- fresh

refresh:
    cd migration; DATABASE_URL={{DATABASE_URL}} cargo run -- refresh

gen-ts:
    typeshare . --lang=typescript --output-file={{TS_OUTPUT}}
    cd ../frontend; pnpm i; pnpm format-ffi

gen-entity:
    sea-orm-cli generate entity -u sqlite://db.sqlite -o entity/src/entities
    open "entity/src/entities/user.rs" | str replace "preference: String" "preference: crate::UserPreference" | save "entity/src/entities/user.rs" -f
    open "entity/src/entities/message.rs" | str replace "kind: i32" "kind: crate::MessageKind" | save "entity/src/entities/message.rs" -f
