TS_OUTPUT := "../frontend/src/lib/api/types.ts"

DATABASE_URL := "sqlite://../db.sqlite?mode=rwc"


run:
    RUST_BACKTRACE=1 RUST_LOG=info cargo run

fresh:
    cd migration; DATABASE_URL={{DATABASE_URL}} cargo run -- fresh

refresh:
    cd migration; DATABASE_URL={{DATABASE_URL}} cargo run -- refresh

gen-ts:
    typeshare . --lang=typescript --output-file={{TS_OUTPUT}}

gen-entity:
    sea-orm-cli generate entity -u sqlite://db.sqlite -o entity/src/entities
