set shell := ["nu", "-c"]

TS_OUTPUT := "../frontend/src/lib/api/types.ts"

DATA_PATH := ".."

BIND_ADDR := "127.0.0.1:8001"

run:
    RUST_BACKTRACE=1 RUST_LOG=trace BIND_ADDR={{BIND_ADDR}} cargo run --features dev

fresh:
    cd migration; DATA_PATH={{DATA_PATH}} cargo run -- fresh

refresh:
    cd migration; DATA_PATH={{DATA_PATH}} cargo run -- refresh

gen-ts:
    typeshare . --lang=typescript --output-file={{TS_OUTPUT}}
    cd ../frontend; pnpm i; pnpm format-ffi

gen-entity:
    sea-orm-cli generate entity -u sqlite://db.sqlite -o entity/src/entities
    open "entity/src/entities/user.rs" | str replace "preference: String" "preference: crate::UserPreference" | save "entity/src/entities/user.rs" -f
    open "entity/src/entities/message.rs" | str replace "kind: i32" "kind: crate::MessageKind" | save "entity/src/entities/message.rs" -f
    open "entity/src/entities/chunk.rs" | str replace "kind: i32" "kind: crate::ChunkKind" | save "entity/src/entities/chunk.rs" -f
