services:
  llumen:
    image: ghcr.io/pinkfuwa/llumen:latest
    restart: on-failure:4
    environment:
      - "API_KEY=your-api-key"
      - "API_BASE=https://ollama.com"
    volumes:
      - "./data:/data"
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          memory: 512M
    memswap_limit: 512M
